### PR TITLE
WIP: Navbar fixed

### PR DESCRIPTION
**Pull request by thiagobraga**
- Removed `plugin-proposal-class-properties` from `.babelrc` to fix the error below
image
image

### CODE REVIEW

**Comment by thesocialdev** [comment]
@thiagobraga the CI error was my fault, rebasing stage will make your patch work again

**Comment by thiagobraga** [comment]
> @thiagobraga the CI error was my fault, rebasing stage will make your patch work again

Done!
Thanks, bro.

**Comment by thesocialdev** [comment]
@thiagobraga what do you think about teaching the team about this PR and maybe we can merge at least the VSCode commands?

**Comment by thiagobraga** [comment]
@thesocialdev :headphones: YESSS hahaha
Nice idea. I would like to talk about this.

**Pull request closed without merging**
